// Generated by gencpp from file my_service/WheelResponse.msg
// DO NOT EDIT!


#ifndef MY_SERVICE_MESSAGE_WHEELRESPONSE_H
#define MY_SERVICE_MESSAGE_WHEELRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_service
{
template <class ContainerAllocator>
struct WheelResponse_
{
  typedef WheelResponse_<ContainerAllocator> Type;

  WheelResponse_()
    : current_linear_velocity(0.0)
    , current_angular_velocity(0.0)  {
    }
  WheelResponse_(const ContainerAllocator& _alloc)
    : current_linear_velocity(0.0)
    , current_angular_velocity(0.0)  {
  (void)_alloc;
    }



   typedef double _current_linear_velocity_type;
  _current_linear_velocity_type current_linear_velocity;

   typedef double _current_angular_velocity_type;
  _current_angular_velocity_type current_angular_velocity;





  typedef boost::shared_ptr< ::my_service::WheelResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_service::WheelResponse_<ContainerAllocator> const> ConstPtr;

}; // struct WheelResponse_

typedef ::my_service::WheelResponse_<std::allocator<void> > WheelResponse;

typedef boost::shared_ptr< ::my_service::WheelResponse > WheelResponsePtr;
typedef boost::shared_ptr< ::my_service::WheelResponse const> WheelResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_service::WheelResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_service::WheelResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace my_service

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::my_service::WheelResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_service::WheelResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_service::WheelResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_service::WheelResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_service::WheelResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_service::WheelResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_service::WheelResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "056d03b83b9853a858cfe23bcf52551d";
  }

  static const char* value(const ::my_service::WheelResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x056d03b83b9853a8ULL;
  static const uint64_t static_value2 = 0x58cfe23bcf52551dULL;
};

template<class ContainerAllocator>
struct DataType< ::my_service::WheelResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_service/WheelResponse";
  }

  static const char* value(const ::my_service::WheelResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_service::WheelResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 current_linear_velocity\n\
float64 current_angular_velocity\n\
\n\
\n\
";
  }

  static const char* value(const ::my_service::WheelResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_service::WheelResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.current_linear_velocity);
      stream.next(m.current_angular_velocity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WheelResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_service::WheelResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_service::WheelResponse_<ContainerAllocator>& v)
  {
    s << indent << "current_linear_velocity: ";
    Printer<double>::stream(s, indent + "  ", v.current_linear_velocity);
    s << indent << "current_angular_velocity: ";
    Printer<double>::stream(s, indent + "  ", v.current_angular_velocity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_SERVICE_MESSAGE_WHEELRESPONSE_H
