(cl:in-package my_service-srv)
(cl:export '(TARGET_LINEAR_VELOCITY-VAL
          TARGET_LINEAR_VELOCITY
          TARGET_ANGULAR_VELOCITY-VAL
          TARGET_ANGULAR_VELOCITY
          CURRENT_LINEAR_VELOCITY-VAL
          CURRENT_LINEAR_VELOCITY
          CURRENT_ANGULAR_VELOCITY-VAL
          CURRENT_ANGULAR_VELOCITY
))